[settings]

guild = 1234567891011121314

[settings.verify]

role = 1234567891011121314
welcome_channel = 1234567891011121314

[settings.status]

type = ""
content = ""

[db]

dbType = ""
host = "localhost"
port = 5432
user = ""
password = ""
dbName = ""
